"""
backend/app/services/ai_service.py
Provider-agnostic clinical AI copilot for MedIndia HealthOS.
Strictly grounded in verifiable EHR records.
"""

from typing import Dict, Any, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload
from backend.app.models.entities import Patient, Condition, Prescription, Encounter, LabOrder, Observation, DiagnosticReport
from backend.app.core.config import settings

class ClinicalAIService:
    DISCLAIMER = (
        "CONFIDENTIAL MEDICAL ADVICE NOTICE: This clinical synthesis was generated by MedIndia "
        "HealthOS AI Decision Support. It is intended solely as an informational assistant for licensed "
        "medical practitioners and does not constitute an autonomous medical diagnosis or prescription."
    )

    PATIENT_DISCLAIMER = (
        "PATIENT INFORMATION NOTICE: This summary explains your laboratory values in simplified terms "
        "for your personal understanding. It does NOT replace professional medical consultation. "
        "Please discuss all laboratory results directly with your treating physician."
    )

    async def get_patient_clinical_dossier(self, patient_id: str, db: AsyncSession) -> Dict[str, Any]:
        """
        Retrieves all structured medical history for a patient to construct
        a strictly grounded clinical context envelope.
        """
        # 1. Patient profile
        p_stmt = select(Patient).where(Patient.id == patient_id).options(selectinload(Patient.user))
        res = await db.execute(p_stmt)
        patient = res.scalar_one_or_none()
        if not patient:
            return {}

        # 2. Conditions
        c_stmt = select(Condition).where(Condition.patient_id == patient_id)
        conditions = (await db.execute(c_stmt)).scalars().all()

        # 3. Prescriptions
        rx_stmt = select(Prescription).where(Prescription.patient_id == patient_id)
        prescriptions = (await db.execute(rx_stmt)).scalars().all()

        # 4. Encounters
        enc_stmt = select(Encounter).where(Encounter.patient_id == patient_id)
        encounters = (await db.execute(enc_stmt)).scalars().all()

        # 5. Lab orders & observations
        lo_stmt = select(LabOrder).where(LabOrder.patient_id == patient_id).options(
            selectinload(LabOrder.observations),
            selectinload(LabOrder.diagnostic_report)
        )
        lab_orders = (await db.execute(lo_stmt)).scalars().all()

        return {
            "patient": patient,
            "conditions": conditions,
            "prescriptions": prescriptions,
            "encounters": encounters,
            "lab_orders": lab_orders
        }

    async def generate_clinical_summary(self, patient_id: str, db: AsyncSession) -> Dict[str, Any]:
        dossier = await self.get_patient_clinical_dossier(patient_id, db)
        if not dossier:
            return {
                "patient_id": patient_id,
                "summary": "Patient medical record not found.",
                "active_conditions": [],
                "active_medications": [],
                "recent_labs": [],
                "grounded_record_ids": [],
                "disclaimer": self.DISCLAIMER
            }

        patient: Patient = dossier["patient"]
        conditions: List[Condition] = dossier["conditions"]
        prescriptions: List[Prescription] = dossier["prescriptions"]
        encounters: List[Encounter] = dossier["encounters"]
        lab_orders: List[LabOrder] = dossier["lab_orders"]

        active_conds = [f"{c.display_name} (SNOMED: {c.snomed_code}) [Condition#{c.id[:8]}]" for c in conditions if c.clinical_status == "ACTIVE"]
        active_rxs = [f"{p.medication_name} {p.dosage}, {p.frequency} [Rx#{p.id[:8]}]" for p in prescriptions if p.status == "ACTIVE"]
        
        recent_labs = []
        grounded_ids = []
        for c in conditions:
            grounded_ids.append(f"Condition:{c.id}")
        for p in prescriptions:
            grounded_ids.append(f"Prescription:{p.id}")
        for e in encounters:
            grounded_ids.append(f"Encounter:{e.id}")

        for lo in lab_orders:
            grounded_ids.append(f"LabOrder:{lo.id}")
            if lo.diagnostic_report:
                grounded_ids.append(f"Report:{lo.diagnostic_report.id}")
            for obs in lo.observations:
                status_flag = "⚠️ ABNORMAL" if obs.is_abnormal else "Normal"
                recent_labs.append(f"{obs.test_name}: {obs.value} {obs.unit or ''} ({status_flag}) [Obs#{obs.id[:8]}]")
                grounded_ids.append(f"Observation:{obs.id}")

        patient_name = patient.user.full_name if patient.user else "Patient"
        dob = patient.date_of_birth or "Unknown DOB"
        gender = patient.gender or "Unknown"

        summary_text = (
            f"Patient {patient_name} ({gender}, DOB: {dob}, ABHA: {patient.abha_id}) has "
            f"{len(active_conds)} active documented conditions and {len(active_rxs)} active prescriptions. "
        )
        if active_conds:
            summary_text += f"Primary active diagnoses include {', '.join(active_conds)}. "
        if active_rxs:
            summary_text += f"Current pharmacological regimen includes: {', '.join(active_rxs)}. "
        if recent_labs:
            summary_text += f"Recent investigations reveal: {'; '.join(recent_labs[:4])}."

        return {
            "patient_id": patient_id,
            "summary": summary_text,
            "active_conditions": active_conds,
            "active_medications": active_rxs,
            "recent_labs": recent_labs,
            "grounded_record_ids": grounded_ids,
            "disclaimer": self.DISCLAIMER
        }

    async def ask_patient_history(self, patient_id: str, query: str, db: AsyncSession) -> Dict[str, Any]:
        dossier = await self.get_patient_clinical_dossier(patient_id, db)
        if not dossier:
            return {
                "query": query,
                "answer": "Patient medical record not found.",
                "grounded_record_ids": [],
                "confidence": "LOW",
                "disclaimer": self.DISCLAIMER
            }

        q_lower = query.lower()
        conditions: List[Condition] = dossier["conditions"]
        prescriptions: List[Prescription] = dossier["prescriptions"]
        encounters: List[Encounter] = dossier["encounters"]
        lab_orders: List[LabOrder] = dossier["lab_orders"]

        matched_ids = []
        matched_sentences = []

        if any(w in q_lower for w in ["lab", "test", "result", "blood", "sugar", "cbc", "glucose", "investigation"]):
            for lo in lab_orders:
                matched_ids.append(f"LabOrder:{lo.id}")
                for obs in lo.observations:
                    matched_ids.append(f"Observation:{obs.id}")
                    flag = " (marked ABNORMAL)" if obs.is_abnormal else ""
                    ref = f" [Ref: {obs.reference_range}]" if obs.reference_range else ""
                    matched_sentences.append(
                        f"• {obs.test_name} recorded on {obs.observation_date.strftime('%Y-%m-%d')}: "
                        f"{obs.value} {obs.unit or ''}{flag}{ref} (Record ID: Obs#{obs.id[:8]})."
                    )

        if any(w in q_lower for w in ["medication", "medicine", "drug", "prescription", "prescribe", "dose", "rx"]):
            for rx in prescriptions:
                matched_ids.append(f"Prescription:{rx.id}")
                matched_sentences.append(
                    f"• Prescribed {rx.medication_name} ({rx.dosage}, {rx.frequency}) for {rx.duration}. "
                    f"Status: {rx.status} (Record ID: Rx#{rx.id[:8]})."
                )

        if any(w in q_lower for w in ["diagnosis", "condition", "disease", "illness", "symptom"]):
            for c in conditions:
                matched_ids.append(f"Condition:{c.id}")
                matched_sentences.append(
                    f"• Diagnosed with {c.display_name} (SNOMED: {c.snomed_code}), Status: {c.clinical_status}, "
                    f"Severity: {c.severity} (Record ID: Condition#{c.id[:8]})."
                )

        if any(w in q_lower for w in ["consultation", "encounter", "visit", "doctor", "appointment"]):
            for enc in encounters:
                matched_ids.append(f"Encounter:{enc.id}")
                matched_sentences.append(
                    f"• Consultation on {enc.encounter_date.strftime('%Y-%m-%d')}: {enc.reason or 'Routine checkup'}. "
                    f"Clinical Notes: {enc.clinical_notes or 'None'} (Record ID: Encounter#{enc.id[:8]})."
                )

        if not matched_sentences:
            # Fallback to general dossier summary
            summary = await self.generate_clinical_summary(patient_id, db)
            answer = f"Based on the patient's records: {summary['summary']}"
            matched_ids = summary["grounded_record_ids"]
        else:
            answer = f"Relevant records retrieved for inquiry '{query}':\n" + "\n".join(matched_sentences)

        return {
            "query": query,
            "answer": answer,
            "grounded_record_ids": matched_ids,
            "confidence": "HIGH" if matched_ids else "MEDIUM",
            "disclaimer": self.DISCLAIMER
        }

    async def explain_lab_report(self, diagnostic_report_id: str, db: AsyncSession) -> Dict[str, Any]:
        stmt = select(DiagnosticReport).where(DiagnosticReport.id == diagnostic_report_id).options(
            selectinload(DiagnosticReport.lab_order).selectinload(LabOrder.observations)
        )
        res = await db.execute(stmt)
        report = res.scalar_one_or_none()
        if not report or not report.lab_order:
            return {
                "report_id": diagnostic_report_id,
                "title": "Report Not Found",
                "explanation": "Diagnostic report could not be found in the database.",
                "key_findings": [],
                "disclaimer": self.PATIENT_DISCLAIMER
            }

        observations = report.lab_order.observations
        key_findings = []
        abnormal_items = []
        normal_items = []

        for obs in observations:
            desc = f"{obs.test_name}: {obs.value} {obs.unit or ''} (Normal range: {obs.reference_range or 'N/A'})"
            key_findings.append(desc)
            if obs.is_abnormal:
                abnormal_items.append(f"{obs.test_name} ({obs.value} {obs.unit or ''}) is outside the normal physiological range.")
            else:
                normal_items.append(f"{obs.test_name} ({obs.value} {obs.unit or ''}) is within normal expected parameters.")

        explanation_parts = [f"This diagnostic report is titled '{report.title}'. "]
        if report.conclusion:
            explanation_parts.append(f"The laboratory conclusion states: {report.conclusion}. ")
        if abnormal_items:
            explanation_parts.append(f"Attention items: {' '.join(abnormal_items)} ")
        if normal_items:
            explanation_parts.append(f"Reassuring findings: {' '.join(normal_items)}")

        return {
            "report_id": diagnostic_report_id,
            "title": report.title,
            "explanation": "".join(explanation_parts),
            "key_findings": key_findings,
            "disclaimer": self.PATIENT_DISCLAIMER
        }

ai_service = ClinicalAIService()
