"""
backend/app/services/ai_service.py
Provider-agnostic clinical AI copilot for MedIndia HealthOS.
Strictly grounded in verifiable EHR records.
"""

from typing import Dict, Any, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload
from backend.app.models.entities import Patient, Condition, Prescription, Encounter, LabOrder, Observation, DiagnosticReport
from backend.app.core.config import settings

class ClinicalAIService:
    DISCLAIMER = (
        "CONFIDENTIAL MEDICAL ADVICE NOTICE: This clinical synthesis was generated by MedIndia "
        "HealthOS AI Decision Support. It is intended solely as an informational assistant for licensed "
        "medical practitioners and does not constitute an autonomous medical diagnosis or prescription."
    )

    PATIENT_DISCLAIMER = (
        "PATIENT INFORMATION NOTICE: This summary explains your laboratory values in simplified terms "
        "for your personal understanding. It does NOT replace professional medical consultation. "
        "Please discuss all laboratory results directly with your treating physician."
    )

    async def get_patient_clinical_dossier(self, patient_id: str, db: AsyncSession) -> Dict[str, Any]:
        """
        Retrieves all structured medical history for a patient to construct
        a strictly grounded clinical context envelope.
        """
        # 1. Patient profile
        p_stmt = select(Patient).where(Patient.id == patient_id).options(selectinload(Patient.user))
        res = await db.execute(p_stmt)
        patient = res.scalar_one_or_none()
        if not patient:
            return {}

        # 2. Conditions
        c_stmt = select(Condition).where(Condition.patient_id == patient_id)
        conditions = (await db.execute(c_stmt)).scalars().all()

        # 3. Prescriptions
        rx_stmt = select(Prescription).where(Prescription.patient_id == patient_id)
        prescriptions = (await db.execute(rx_stmt)).scalars().all()

        # 4. Encounters
        enc_stmt = select(Encounter).where(Encounter.patient_id == patient_id)
        encounters = (await db.execute(enc_stmt)).scalars().all()

        # 5. Lab orders & observations
        lo_stmt = select(LabOrder).where(LabOrder.patient_id == patient_id).options(
            selectinload(LabOrder.observations),
            selectinload(LabOrder.diagnostic_report)
        )
        lab_orders = (await db.execute(lo_stmt)).scalars().all()

        return {
            "patient": patient,
            "conditions": conditions,
            "prescriptions": prescriptions,
            "encounters": encounters,
            "lab_orders": lab_orders
        }

    async def generate_clinical_summary(self, patient_id: str, db: AsyncSession) -> Dict[str, Any]:
        dossier = await self.get_patient_clinical_dossier(patient_id, db)
        if not dossier:
            return {
                "patient_id": patient_id,
                "summary": "Patient medical record not found.",
                "active_conditions": [],
                "active_medications": [],
                "recent_labs": [],
                "grounded_record_ids": [],
                "disclaimer": self.DISCLAIMER
            }

        patient: Patient = dossier["patient"]
        conditions: List[Condition] = dossier["conditions"]
        prescriptions: List[Prescription] = dossier["prescriptions"]
        encounters: List[Encounter] = dossier["encounters"]
        lab_orders: List[LabOrder] = dossier["lab_orders"]

        active_conds = [f"{c.display_name} (SNOMED: {c.snomed_code}) [Condition#{c.id[:8]}]" for c in conditions if c.clinical_status == "ACTIVE"]
        active_rxs = [f"{p.medication_name} {p.dosage}, {p.frequency} [Rx#{p.id[:8]}]" for p in prescriptions if p.status == "ACTIVE"]
        
        recent_labs = []
        grounded_ids = []
        for c in conditions:
            grounded_ids.append(f"Condition:{c.id}")
        for p in prescriptions:
            grounded_ids.append(f"Prescription:{p.id}")
        for e in encounters:
            grounded_ids.append(f"Encounter:{e.id}")

        for lo in lab_orders:
            grounded_ids.append(f"LabOrder:{lo.id}")
            if lo.diagnostic_report:
                grounded_ids.append(f"Report:{lo.diagnostic_report.id}")
            for obs in lo.observations:
                status_flag = "⚠️ ABNORMAL" if obs.is_abnormal else "Normal"
                recent_labs.append(f"{obs.test_name}: {obs.value} {obs.unit or ''} ({status_flag}) [Obs#{obs.id[:8]}]")
                grounded_ids.append(f"Observation:{obs.id}")

        patient_name = patient.user.full_name if patient.user else "Patient"
        dob = patient.date_of_birth or "Unknown DOB"
        gender = patient.gender or "Unknown"

        summary_text = (
            f"Patient {patient_name} ({gender}, DOB: {dob}, ABHA: {patient.abha_id}) has "
            f"{len(active_conds)} active documented conditions and {len(active_rxs)} active prescriptions. "
        )
        if active_conds:
            summary_text += f"Primary active diagnoses include {', '.join(active_conds)}. "
        if active_rxs:
            summary_text += f"Current pharmacological regimen includes: {', '.join(active_rxs)}. "
        if recent_labs:
            summary_text += f"Recent investigations reveal: {'; '.join(recent_labs[:4])}."

        return {
            "patient_id": patient_id,
            "summary": summary_text,
            "active_conditions": active_conds,
            "active_medications": active_rxs,
            "recent_labs": recent_labs,
            "grounded_record_ids": grounded_ids,
            "disclaimer": self.DISCLAIMER
        }

    async def ask_patient_history(self, patient_id: str, query: str, db: AsyncSession) -> Dict[str, Any]:
        dossier = await self.get_patient_clinical_dossier(patient_id, db)
        if not dossier:
            return {
                "query": query,
                "answer": "Patient medical record not found.",
                "grounded_record_ids": [],
                "confidence": "LOW",
                "disclaimer": self.DISCLAIMER
            }

        q_lower = query.lower()
        conditions: List[Condition] = dossier["conditions"]
        prescriptions: List[Prescription] = dossier["prescriptions"]
        encounters: List[Encounter] = dossier["encounters"]
        lab_orders: List[LabOrder] = dossier["lab_orders"]

        matched_ids = []
        matched_sentences = []

        if any(w in q_lower for w in ["lab", "test", "result", "blood", "sugar", "cbc", "glucose", "investigation"]):
            for lo in lab_orders:
                matched_ids.append(f"LabOrder:{lo.id}")
                for obs in lo.observations:
                    matched_ids.append(f"Observation:{obs.id}")
                    flag = " (marked ABNORMAL)" if obs.is_abnormal else ""
                    ref = f" [Ref: {obs.reference_range}]" if obs.reference_range else ""
                    matched_sentences.append(
                        f"• {obs.test_name} recorded on {obs.observation_date.strftime('%Y-%m-%d')}: "
                        f"{obs.value} {obs.unit or ''}{flag}{ref} (Record ID: Obs#{obs.id[:8]})."
                    )

        if any(w in q_lower for w in ["medication", "medicine", "drug", "prescription", "prescribe", "dose", "rx"]):
            for rx in prescriptions:
                matched_ids.append(f"Prescription:{rx.id}")
                matched_sentences.append(
                    f"• Prescribed {rx.medication_name} ({rx.dosage}, {rx.frequency}) for {rx.duration}. "
                    f"Status: {rx.status} (Record ID: Rx#{rx.id[:8]})."
                )

        if any(w in q_lower for w in ["diagnosis", "condition", "disease", "illness", "symptom"]):
            for c in conditions:
                matched_ids.append(f"Condition:{c.id}")
                matched_sentences.append(
                    f"• Diagnosed with {c.display_name} (SNOMED: {c.snomed_code}), Status: {c.clinical_status}, "
                    f"Severity: {c.severity} (Record ID: Condition#{c.id[:8]})."
                )

        if any(w in q_lower for w in ["consultation", "encounter", "visit", "doctor", "appointment"]):
            for enc in encounters:
                matched_ids.append(f"Encounter:{enc.id}")
                matched_sentences.append(
                    f"• Consultation on {enc.encounter_date.strftime('%Y-%m-%d')}: {enc.reason or 'Routine checkup'}. "
                    f"Clinical Notes: {enc.clinical_notes or 'None'} (Record ID: Encounter#{enc.id[:8]})."
                )

        if not matched_sentences:
            # Fallback to general dossier summary
            summary = await self.generate_clinical_summary(patient_id, db)
            answer = f"Based on the patient's records: {summary['summary']}"
            matched_ids = summary["grounded_record_ids"]
        else:
            answer = f"Relevant records retrieved for inquiry '{query}':\n" + "\n".join(matched_sentences)

        return {
            "query": query,
            "answer": answer,
            "grounded_record_ids": matched_ids,
            "confidence": "HIGH" if matched_ids else "MEDIUM",
            "disclaimer": self.DISCLAIMER
        }

    async def explain_lab_report(self, diagnostic_report_id: str, db: AsyncSession) -> Dict[str, Any]:
        stmt = select(DiagnosticReport).where(DiagnosticReport.id == diagnostic_report_id).options(
            selectinload(DiagnosticReport.lab_order).selectinload(LabOrder.observations)
        )
        res = await db.execute(stmt)
        report = res.scalar_one_or_none()
        if not report or not report.lab_order:
            return {
                "report_id": diagnostic_report_id,
                "title": "Report Not Found",
                "explanation": "Diagnostic report could not be found in the database.",
                "key_findings": [],
                "disclaimer": self.PATIENT_DISCLAIMER
            }

        observations = report.lab_order.observations
        key_findings = []
        abnormal_items = []
        normal_items = []

        for obs in observations:
            desc = f"{obs.test_name}: {obs.value} {obs.unit or ''} (Normal range: {obs.reference_range or 'N/A'})"
            key_findings.append(desc)
            if obs.is_abnormal:
                abnormal_items.append(f"{obs.test_name} ({obs.value} {obs.unit or ''}) is outside the normal physiological range.")
            else:
                normal_items.append(f"{obs.test_name} ({obs.value} {obs.unit or ''}) is within normal expected parameters.")

        explanation_parts = [f"This diagnostic report is titled '{report.title}'. "]
        if report.conclusion:
            explanation_parts.append(f"The laboratory conclusion states: {report.conclusion}. ")
        if abnormal_items:
            explanation_parts.append(f"Attention items: {' '.join(abnormal_items)} ")
        if normal_items:
            explanation_parts.append(f"Reassuring findings: {' '.join(normal_items)}")

        return {
            "report_id": diagnostic_report_id,
            "title": report.title,
            "explanation": "".join(explanation_parts),
            "key_findings": key_findings,
            "disclaimer": self.PATIENT_DISCLAIMER
        }

    def parse_dictation(self, transcript: str) -> Dict[str, Any]:
        """
        Extracts structured clinical consultation entities from dictated clinical speech:
        1. Chief Complaint & Reason
        2. Clinical Narrative Notes
        3. SNOMED CT Coded Conditions
        4. Structured Prescriptions (drug, dose, freq, duration)
        5. Lab Test Requisitions
        """
        t = transcript.strip()
        t_lower = t.lower()

        # 1. Detect Reason
        reason = "Clinical Consultation"
        if "presents with" in t_lower:
            parts = t_lower.split("presents with", 1)[1].split(".")[0].strip()
            reason = f"Evaluation of {parts.capitalize()}"
        elif "complaining of" in t_lower:
            parts = t_lower.split("complaining of", 1)[1].split(".")[0].strip()
            reason = f"Symptoms of {parts.capitalize()}"
        elif "follow-up" in t_lower:
            reason = "Clinical Follow-up & Review"
        elif "fever" in t_lower:
            reason = "Acute Febrile Illness Workup"
        elif "cough" in t_lower:
            reason = "Respiratory Symptoms Evaluation"
        elif "chest pain" in t_lower:
            reason = "Chest Discomfort & Cardiology Review"

        # 2. Extract Conditions from SNOMED catalog
        conditions = []
        matched_codes = set()
        condition_triggers = [
            ("acute bronchitis", "10509002", "Acute bronchitis", "MODERATE"),
            ("bronchitis", "10509002", "Acute bronchitis", "MODERATE"),
            ("type 2 diabetes", "44054006", "Type 2 diabetes mellitus", "CHRONIC"),
            ("t2dm", "44054006", "Type 2 diabetes mellitus", "CHRONIC"),
            ("gestational diabetes", "11687002", "Gestational diabetes mellitus", "MODERATE"),
            ("hypertension", "59621000", "Essential hypertension", "CHRONIC"),
            ("high blood pressure", "59621000", "Essential hypertension", "CHRONIC"),
            ("dengue", "38362002", "Dengue fever", "SEVERE"),
            ("thrombocytopenia", "302215000", "Thrombocytopenia", "SEVERE"),
            ("asthma", "195967001", "Asthma", "MODERATE"),
            ("pneumonia", "53084003", "Bacterial pneumonia", "SEVERE"),
            ("malaria", "61462000", "Malaria", "SEVERE"),
            ("ischemic heart disease", "53741008", "Coronary arteriosclerosis", "SEVERE"),
            ("coronary", "53741008", "Coronary arteriosclerosis", "SEVERE"),
            ("heart attack", "22298006", "Acute myocardial infarction", "SEVERE"),
            ("myocardial infarction", "22298006", "Acute myocardial infarction", "SEVERE"),
            ("hypothyroidism", "40930008", "Primary hypothyroidism", "CHRONIC"),
            ("hyperlipidemia", "55822004", "Hyperlipidemia", "CHRONIC"),
            ("gerd", "235595009", "Gastroesophageal reflux disease", "MILD"),
            ("chest pain", "29857009", "Chest pain", "MODERATE"),
            ("fever", "386661006", "Fever", "MILD"),
            ("cough", "49727002", "Cough", "MILD"),
            ("headache", "25064002", "Headache", "MILD"),
        ]

        for trigger, code, display, severity in condition_triggers:
            if trigger in t_lower and code not in matched_codes:
                matched_codes.add(code)
                conditions.append({
                    "snomed_code": code,
                    "display_name": display,
                    "clinical_status": "ACTIVE",
                    "severity": severity,
                    "notes": f"Identified from clinical dictation: '{trigger}'"
                })

        # 3. Extract Prescriptions
        prescriptions = []
        med_catalogs = [
            ("amoxicillin", "Amoxicillin", "500 mg", "Three times daily after meals", "5 days"),
            ("azithromycin", "Azithromycin", "500 mg", "Once daily before food", "3 days"),
            ("paracetamol", "Paracetamol", "650 mg", "SOS (Every 6-8 hours as needed for fever)", "5 days"),
            ("dolo", "Dolo 650", "650 mg", "SOS (Every 6 hours as needed for fever)", "5 days"),
            ("metformin", "Metformin Hydrochloride", "500 mg", "Twice daily with meals", "30 days"),
            ("telmisartan", "Telmisartan", "40 mg", "Once daily in the morning", "30 days"),
            ("atorvastatin", "Atorvastatin Calcium", "20 mg", "Once daily at bedtime", "30 days"),
            ("aspirin", "Aspirin (Ecosprin)", "75 mg", "Once daily after lunch", "30 days"),
            ("metoprolol", "Metoprolol Succinate", "25 mg", "Once daily in the morning", "30 days"),
            ("levothyroxine", "Levothyroxine Sodium", "75 mcg", "Once daily early morning empty stomach", "30 days"),
            ("pantoprazole", "Pantoprazole", "40 mg", "Once daily before breakfast", "14 days"),
            ("insulin", "Regular Human Insulin", "4 units", "Twice daily before meals", "30 days"),
            ("montelukast", "Montelukast", "10 mg", "Once daily at bedtime", "10 days"),
            ("cetirizine", "Cetirizine", "10 mg", "Once daily at bedtime", "7 days")
        ]

        for med_key, med_name, def_dosage, def_freq, def_dur in med_catalogs:
            if med_key in t_lower:
                dosage = def_dosage
                if "1000 mg" in t_lower or "1g" in t_lower:
                    if med_key == "metformin":
                        dosage = "1000 mg"
                elif "500 mg" in t_lower:
                    dosage = "500 mg"
                elif "650 mg" in t_lower:
                    dosage = "650 mg"
                elif "40 mg" in t_lower:
                    dosage = "40 mg"
                elif "20 mg" in t_lower:
                    dosage = "20 mg"

                frequency = def_freq
                if "three times daily" in t_lower or "tds" in t_lower:
                    frequency = "Three times daily after meals"
                elif "twice daily" in t_lower or "bd" in t_lower:
                    frequency = "Twice daily after meals"
                elif "once daily" in t_lower or "od" in t_lower:
                    frequency = "Once daily"
                elif "sos" in t_lower or "as needed" in t_lower:
                    frequency = "SOS (As needed for symptoms)"

                duration = def_dur
                if "5 days" in t_lower:
                    duration = "5 days"
                elif "7 days" in t_lower or "1 week" in t_lower:
                    duration = "7 days"
                elif "10 days" in t_lower:
                    duration = "10 days"
                elif "14 days" in t_lower or "2 weeks" in t_lower:
                    duration = "14 days"
                elif "30 days" in t_lower or "1 month" in t_lower:
                    duration = "30 days"

                prescriptions.append({
                    "medication_name": med_name,
                    "dosage": dosage,
                    "frequency": frequency,
                    "duration": duration,
                    "instructions": "Take as prescribed. Maintain adequate hydration."
                })

        # 4. Extract Lab Orders
        lab_orders = []
        test_catalogs = [
            (["complete blood count", "cbc", "blood count"], "58800005", "Complete Blood Count (CBC)"),
            (["platelet", "platelets"], "43789009", "Platelet Count Measurement"),
            (["hba1c", "glycated hemoglobin"], "43396009", "Hemoglobin A1c Measurement"),
            (["fasting blood sugar", "blood glucose", "fbs"], "33747003", "Fasting Blood Glucose"),
            (["lipid profile", "lipid panel"], "396550006", "Comprehensive Lipid Panel"),
            (["creatinine", "serum creatinine", "kft"], "275711006", "Serum Creatinine & eGFR"),
            (["liver function", "lft"], "26958001", "Liver Function Tests"),
            (["dengue ns1", "dengue antigen"], "252275004", "Dengue NS1 Antigen Rapid Test"),
            (["tsh", "thyroid"], "396560005", "Serum Thyroid Stimulating Hormone (TSH)"),
            (["urine microalbumin"], "271062006", "Urine Microalbumin & Creatinine Ratio"),
            (["electrolytes", "serum electrolytes"], "104177005", "Serum Electrolytes Panel")
        ]

        for synonyms, code, test_name in test_catalogs:
            if any(syn in t_lower for syn in synonyms):
                priority = "ROUTINE"
                if "stat" in t_lower or "immediately" in t_lower:
                    priority = "STAT"
                elif "urgent" in t_lower or "repeat" in t_lower:
                    priority = "URGENT"

                lab_orders.append({
                    "test_name": test_name,
                    "test_code": code,
                    "priority": priority
                })

        clean_notes = (
            f"DICTATED CLINICAL ENCOUNTER:\n{t}\n\n"
            f"Clinical Assessment: {', '.join([c['display_name'] for c in conditions]) or 'Unspecified clinical presentation'}.\n"
            f"Plan: Prescribed {len(prescriptions)} medication(s), ordered {len(lab_orders)} diagnostic test(s)."
        )

        return {
            "reason": reason,
            "clinical_notes": clean_notes,
            "conditions": conditions,
            "prescriptions": prescriptions,
            "lab_orders": lab_orders,
            "raw_transcript": t
        }

ai_service = ClinicalAIService()

